# Generated by Django 4.1.2 on 2022-12-02 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Layers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название карты"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Подробное описание карты"),
                ),
                (
                    "from_file",
                    models.FileField(
                        blank=True,
                        help_text="Файл должен быть GEOJSON",
                        null=True,
                        upload_to="media",
                        verbose_name="Слой будет взят из файла",
                    ),
                ),
                (
                    "zabbix_group_name",
                    models.CharField(
                        blank=True,
                        help_text="Все узлы сети из данной группы будут на этом слое",
                        max_length=100,
                        null=True,
                        verbose_name="Имя группы Zabbix",
                    ),
                ),
                (
                    "points_color",
                    models.CharField(
                        default="#00CC00",
                        help_text="Для узла сети Zabbix",
                        max_length=10,
                        verbose_name="Цвет маркера",
                    ),
                ),
                (
                    "points_border_color",
                    models.CharField(
                        default="#fff",
                        help_text="Для узла сети Zabbix",
                        max_length=10,
                        verbose_name="Цвет рамки маркера",
                    ),
                ),
                (
                    "points_radius",
                    models.PositiveSmallIntegerField(
                        help_text="Для узла сети Zabbix",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Радиус маркеров для",
                    ),
                ),
            ],
        ),
    ]
