# Generated by Django 4.1.2 on 2022-12-02 12:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layers",
            options={"verbose_name": "Слой", "verbose_name_plural": "Слои"},
        ),
        migrations.AlterField(
            model_name="layers",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Подробное описание слоя"),
        ),
        migrations.AlterField(
            model_name="layers",
            name="name",
            field=models.CharField(
                help_text="Будет отображаться на карте",
                max_length=100,
                verbose_name="Название слоя",
            ),
        ),
        migrations.AlterField(
            model_name="layers",
            name="points_border_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Для узла сети Zabbix",
                max_length=10,
                verbose_name="Цвет рамки маркера",
            ),
        ),
        migrations.AlterField(
            model_name="layers",
            name="points_radius",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Для узла сети Zabbix",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Радиус маркеров для",
            ),
        ),
        migrations.CreateModel(
            name="Maps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название карты"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Подробное описание карты"),
                ),
                (
                    "interactive",
                    models.BooleanField(
                        default=False,
                        help_text="Автоматическое обновление состояния узлов сети из тех слоев, что созданы через группу Zabbix",
                        verbose_name="Карта будет интерактивной?",
                    ),
                ),
                (
                    "map_url",
                    models.URLField(
                        help_text="URL должен быть абсолютным т.е. содержать обозначение протокола (`http://` или `https://`)",
                        max_length=2048,
                        verbose_name="URL Карты из другого ресурса",
                    ),
                ),
                (
                    "layers",
                    models.ManyToManyField(
                        to="maps.layers",
                        verbose_name="Выберите слои, которые будут на карте",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="Данные пользователи смогут просматривать эту карту",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выберите пользователей",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта",
                "verbose_name_plural": "Карты",
            },
        ),
    ]
