# Generated by Django 4.1.2 on 2022-12-07 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_alter_maps_from_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="layers",
            name="default_geojson_border_color",
            field=models.CharField(
                default="#004c87",
                help_text="Для элементов из файла geojson, у которых не указан цвет рамок в properties",
                max_length=7,
                verbose_name="Цвет рамок по умолчанию",
            ),
        ),
        migrations.AddField(
            model_name="layers",
            name="default_geojson_fill_color",
            field=models.CharField(
                default="#0074CC",
                help_text="Для элементов из файла geojson, у которых не указан цвет в properties",
                max_length=7,
                verbose_name="Цвет по умолчанию",
            ),
        ),
        migrations.AddField(
            model_name="layers",
            name="default_geojson_opacity",
            field=models.FloatField(
                default=0.6,
                help_text="Вещественное число от 0 до 1Для элементов из файла geojson, у которых не указана непрозрачность",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Непрозрачность",
            ),
        ),
        migrations.AlterField(
            model_name="maps",
            name="from_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="templates/maps/external",
                verbose_name="HTML файл карты",
            ),
        ),
    ]
