# Generated by Django 4.1.2 on 2022-12-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_layers_default_geojson_border_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layers",
            old_name="default_geojson_border_color",
            new_name="polygon_border_color",
        ),
        migrations.RenameField(
            model_name="layers",
            old_name="default_geojson_fill_color",
            new_name="polygon_fill_color",
        ),
        migrations.RenameField(
            model_name="layers",
            old_name="default_geojson_opacity",
            new_name="polygon_opacity",
        ),
    ]
