# Generated by Django 4.1.2 on 2022-12-07 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "maps",
            "0008_rename_default_geojson_border_color_layers_polygon_border_color_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layers",
            name="points_radius",
        ),
        migrations.AddField(
            model_name="layers",
            name="points_size",
            field=models.PositiveSmallIntegerField(
                default=7,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(64),
                ],
                verbose_name="Размер маркера (px)",
            ),
        ),
        migrations.AlterField(
            model_name="layers",
            name="points_border_color",
            field=models.CharField(default="#ffffff", max_length=10, verbose_name="Цвет рамки маркера"),
        ),
        migrations.AlterField(
            model_name="layers",
            name="points_color",
            field=models.CharField(default="#00CC00", max_length=10, verbose_name="Цвет маркера"),
        ),
        migrations.AlterField(
            model_name="layers",
            name="polygon_border_color",
            field=models.CharField(default="#004c87", max_length=7, verbose_name="Цвет рамок полигона"),
        ),
        migrations.AlterField(
            model_name="layers",
            name="polygon_fill_color",
            field=models.CharField(default="#0074CC", max_length=7, verbose_name="Цвет полигона"),
        ),
        migrations.AlterField(
            model_name="layers",
            name="polygon_opacity",
            field=models.FloatField(
                default=0.6,
                help_text="Вещественное число от 0 до 1",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Непрозрачность полигона",
            ),
        ),
    ]
