# Generated by Django 4.1.2 on 2022-12-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0009_remove_layers_points_radius_layers_points_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layers",
            name="marker_icon_name",
            field=models.CharField(default="circle-fill", max_length=100, verbose_name="Выберите иконку"),
        ),
    ]
