# Generated by Django 5.1.5 on 2025-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0003_vlantracerouteconfig_cache_timeout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agg_dev_name_regexp",
                    models.TextField(
                        help_text="Оборудования, которые будут использоваться как начало и конец колец доступа",
                        verbose_name="RegExp для названия оборудований агрегации",
                    ),
                ),
                (
                    "access_dev_name_regexp",
                    models.TextField(
                        help_text="Оборудования, которые являются элементами колец доступа",
                        verbose_name="RegExp для названия оборудований доступа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access rings settings",
                "verbose_name_plural": "Access rings settings",
                "db_table": "access_rings_settings",
            },
        ),
    ]
