# Generated by Django 6.0.5 on 2026-06-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0004_accessringsettings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VlanTracerouteConfig",
            new_name="TracerouteConfig",
        ),
        migrations.RenameField(
            model_name="tracerouteconfig",
            old_name="vlan_start",
            new_name="start_device",
        ),
        migrations.RenameField(
            model_name="tracerouteconfig",
            old_name="vlan_start_regex",
            new_name="start_device_regex",
        ),
        migrations.RenameField(
            model_name="tracerouteconfig",
            old_name="ip_pattern",
            new_name="device_ip_pattern",
        ),
        migrations.AlterModelTable(
            name="tracerouteconfig",
            table="traceroute_settings",
        ),
        migrations.AlterModelOptions(
            name="tracerouteconfig",
            options={
                "verbose_name": "Traceroute settings",
                "verbose_name_plural": "Traceroute settings",
            },
        ),
    ]
