# Generated by Django 5.1.5 on 2025-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gathering", "0002_vlan_vlanport_vlan_vlan_index_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vlan",
            old_name="vlan_desc",
            new_name="desc",
        ),
        migrations.RemoveField(
            model_name="vlanport",
            name="desc_port",
        ),
        migrations.AddField(
            model_name="vlanport",
            name="desc",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
