# Generated by Django 4.1.2 on 2022-12-02 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maps", "0002_alter_layers_options_alter_layers_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maps",
            name="layers",
            field=models.ManyToManyField(blank=True, null=True, to="maps.layers", verbose_name="Cлои"),  # type: ignore
        ),
        migrations.AlterField(
            model_name="maps",
            name="map_url",
            field=models.URLField(
                blank=True,
                help_text="URL должен быть абсолютным т.е. содержать обозначение протокола (`http://` или `https://`)",
                max_length=2048,
                null=True,
                verbose_name="URL Карты из другого ресурса",
            ),
        ),
        migrations.AlterField(
            model_name="maps",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователи",
                null=True,  # type: ignore
                to=settings.AUTH_USER_MODEL,
                verbose_name="Выберите пользователей",
            ),
        ),
    ]
