# Generated by Django 4.1.2 on 2022-12-02 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maps", "0003_alter_maps_layers_alter_maps_map_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maps",
            name="layers",
            field=models.ManyToManyField(to="maps.layers", verbose_name="Cлои"),
        ),
        migrations.AlterField(
            model_name="maps",
            name="users",
            field=models.ManyToManyField(
                help_text="Пользователи",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Выберите пользователей",
            ),
        ),
    ]
