# Generated by Django 4.1.2 on 2022-12-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0005_alter_maps_options_maps_from_file_maps_preview_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maps",
            name="from_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="map_files",
                verbose_name="HTML файл карты",
            ),
        ),
    ]
