# Generated by Django 4.2.8 on 2024-03-13 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0010_layers_marker_icon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layers",
            name="points_size",
            field=models.PositiveSmallIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(64),
                ],
                verbose_name="Размер маркера (px)",
            ),
        ),
    ]
