# Generated by Django 6.0.6 on 2026-06-22 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0043_profile_permissions_to_auth_permissions"),
        ("maps", "0011_alter_layers_points_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="layers",
            name="device_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Все устройства из данной группы с координатами будут на этом слое",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="map_layers",
                to="check.devicegroup",
                verbose_name="Группа оборудования",
            ),
        ),
    ]
