# Generated by Django 6.0.7 on 2026-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0012_layers_device_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TileLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название подложки")),
                (
                    "url",
                    models.URLField(
                        help_text="Шаблон URL с параметрами {x}, {y}, {z}",
                        max_length=2048,
                        unique=True,
                        verbose_name="URL тайлов",
                    ),
                ),
                (
                    "crs",
                    models.CharField(
                        choices=[
                            ("EPSG:3857", "EPSG:3857"),
                            ("EPSG:3395", "EPSG:3395"),
                            ("EPSG:4326", "EPSG:4326"),
                        ],
                        default=("EPSG:3857", "EPSG:3857"),
                        help_text="Coordinate Reference System (Система координат)",
                        max_length=20,
                        verbose_name="CRS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подложку карты",
                "verbose_name_plural": "Подложки карт",
                "ordering": ["-id"],
            },
        ),
    ]
