version: "3.10"

volumes:
  redis-data:

services:

  frontend:
    image: nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - "./static:/var/www/static"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend

  redis:
    image: redis
    restart: always
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10

  backend:
    build: .
    image: ecstasy:v17.5.6
    restart: always
    command: /bin/sh run.sh
    volumes:
      - "./db.sqlite3:/app/db.sqlite3"
      - "./run.sh:/app/run.sh"
      - "./logs:/app/logs"
      - "./static:/app/static"
      - "./media:/app/media"
      - "./map_layer_files:/app/media/map_layer_files"
      - "./configurations:/configurations"
    environment:
      ALLOWED_HOSTS: "*"
      REDIS_CACHE_URL: "redis:6379/0"
      DATABASES: |
        {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": "db.sqlite3",
                "OPTIONS": {
                    "timeout": 20
                }
            }
        }
      DJANGO_SECRET_KEY: "9129038921n79sfmmnoYN()!*(*(*(*(*(*(*(#)*@!Y#ASJLSDJF:LJ!{02197390123"
      CONFIG_STORAGE_DIR: "/configurations"

    depends_on:
      redis:
        condition: service_healthy