# Generated by Django 5.0.6 on 2024-05-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                            ("info", "Info"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="info",
                        help_text="Уровень важности сообщения",
                        max_length=16,
                        verbose_name="Важность",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время, до которого будет отображаться сообщение",
                        null=True,
                        verbose_name="Время истечения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Глобальная новость",
                "verbose_name_plural": "Глобальные новости",
                "db_table": "global_news",
                "ordering": ["-created_at"],
            },
        ),
    ]
