# Generated by Django 4.1.4 on 2023-01-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0023_interfacescomments"),
        ("net_tools", "0002_remove_devicesinfo_sys_info_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicesinfo",
            options={},
        ),
        migrations.RemoveField(
            model_name="devicesinfo",
            name="device_name",
        ),
        migrations.RemoveField(
            model_name="devicesinfo",
            name="ip",
        ),
        migrations.AlterField(
            model_name="devicesinfo",
            name="dev",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="check.devices",
            ),
        ),
    ]
