# Generated by Django 6.0.5 on 2026-05-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("net_tools", "0003_alter_devicesinfo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TracerouteNodeKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Стабильный технический код (например: empty_port, unknown_description, uplink_arrow).",
                        max_length=64,
                        unique=True,
                        verbose_name="Код типа",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Человекочитаемое имя типа узла для админки.",
                        max_length=255,
                        verbose_name="Название типа",
                    ),
                ),
                (
                    "marker_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Маркер в сыром ID узла, по которому определяется этот тип (например: p:(, d:(, -->).",
                        max_length=64,
                        verbose_name="Префикс маркера",
                    ),
                ),
                (
                    "marker_suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Закрывающая часть маркера (например: )). Для '-->' обычно пусто.",
                        max_length=64,
                        verbose_name="Суффикс маркера",
                    ),
                ),
                (
                    "value_source",
                    models.CharField(
                        choices=[
                            ("raw", "Raw node value"),
                            ("marker_body", "Text inside marker"),
                            ("after_arrow", "Text after '-->'"),
                        ],
                        default="raw",
                        max_length=32,
                        verbose_name="Источник значения label",
                    ),
                ),
                (
                    "hide_when_nodes_only",
                    models.BooleanField(
                        default=False,
                        help_text="Если включено, узлы этого типа не будут добавляться в граф при nodes_only=true.",
                        verbose_name="Скрывать в режиме only nodes",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Свободное описание назначения типа и примеров использования.",
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "VLAN traceroute node kind",
                "verbose_name_plural": "VLAN traceroute node kinds",
                "db_table": "vlan_traceroute_node_kind",
            },
        ),
        migrations.CreateModel(
            name="TracerouteNodeStyleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Уникальное имя правила для поддержки и отладки.",
                        max_length=255,
                        unique=True,
                        verbose_name="Название правила",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Выключенные правила игнорируются при построении графа.",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Чем меньше число, тем раньше применяется правило.",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("contains", "Contains"),
                            ("exact", "Exact match"),
                            ("starts_with", "Starts with"),
                            ("ends_with", "Ends with"),
                            ("regex", "Regex"),
                        ],
                        default="contains",
                        max_length=20,
                        verbose_name="Тип сопоставления",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Строка/regex для поиска в сыром имени узла. Пусто = без дополнительного условия.",
                        max_length=255,
                        verbose_name="Шаблон сопоставления",
                    ),
                ),
                (
                    "group_id",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional. Used only when explicit colors are not set below.",
                        null=True,
                        verbose_name="Group color (legacy fallback)",
                    ),
                ),
                (
                    "color_background",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Any CSS color: #RRGGBB, rgb(...), hsl(...), var(--token).",
                        max_length=32,
                        verbose_name="Node background color",
                    ),
                ),
                (
                    "color_border",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Any CSS color.",
                        max_length=32,
                        verbose_name="Node border color",
                    ),
                ),
                (
                    "color_font",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Any CSS color.",
                        max_length=32,
                        verbose_name="Node text color",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dot", "Dot"),
                            ("triangle", "Triangle"),
                            ("square", "Square"),
                            ("diamond", "Diamond"),
                            ("box", "Box"),
                        ],
                        help_text="Форма узла vis-network. Если не задана, форма не меняется этим правилом.",
                        max_length=20,
                        null=True,
                        verbose_name="Форма узла",
                    ),
                ),
                (
                    "fixed_value",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Если заполнено — подменяет auto value для узла.",
                        null=True,
                        verbose_name="Фиксированный размер узла",
                    ),
                ),
                (
                    "stop_processing",
                    models.BooleanField(
                        default=True,
                        help_text="Если включено, следующие правила для узла не применяются.",
                        verbose_name="Остановить обработку после совпадения",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "node_kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="style_rules",
                        to="net_tools.traceroutenodekind",
                        verbose_name="Тип узла",
                    ),
                ),
            ],
            options={
                "verbose_name": "VLAN traceroute node style rule",
                "verbose_name_plural": "VLAN traceroute node style rules",
                "db_table": "vlan_traceroute_node_style_rule",
                "ordering": ("priority", "id"),
            },
        ),
    ]
