# Generated by Django 6.0.5 on 2026-06-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("net_tools", "0004_traceroutenodekind_traceroutenodestylerule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="descnameformat",
            options={"verbose_name": "Traceroute desc name format"},
        ),
        migrations.AlterModelOptions(
            name="traceroutenodekind",
            options={"verbose_name": "Traceroute node kind", "verbose_name_plural": "Traceroute node kinds"},
        ),
        migrations.AlterModelOptions(
            name="traceroutenodestylerule",
            options={
                "ordering": ("priority", "id"),
                "verbose_name": "Traceroute node style rule",
                "verbose_name_plural": "Traceroute node style rules",
            },
        ),
        migrations.AlterModelTable(
            name="descnameformat",
            table="traceroute_desc_name_format",
        ),
        migrations.AlterModelTable(
            name="traceroutenodekind",
            table="traceroute_node_kind",
        ),
        migrations.AlterModelTable(
            name="traceroutenodestylerule",
            table="traceroute_node_style_rule",
        ),
    ]
