# Generated by Django 6.0.5 on 2026-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0038_devicecommand_valid_regexp"),
        (
            "gathering",
            "0003_rename_vlan_desc_vlan_desc_remove_vlanport_desc_port_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="desc",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="vlan",
            index=models.Index(fields=["device", "datetime"], name="vlan_device_dt_index"),
        ),
        migrations.AddIndex(
            model_name="vlanport",
            index=models.Index(fields=["port"], name="vlan_port_index"),
        ),
    ]
