# Generated by Django 6.0.8 on 2026-08-11 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0043_profile_permissions_to_auth_permissions"),
        ("gathering", "0004_alter_macaddress_vlan_alter_vlan_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatheringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True, verbose_name="Celery task ID")),
                ("name", models.CharField(max_length=128, verbose_name="Название задачи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILURE", "Failure"),
                        ],
                        db_index=True,
                        default="RUNNING",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("total_devices", models.PositiveIntegerField(default=0, verbose_name="Всего устройств")),
                ("error_type", models.CharField(blank=True, max_length=128, verbose_name="Тип ошибки")),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата начала"),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
            ],
            options={
                "db_table": "gathering_tasks",
                "ordering": ("-started_at",),
                "indexes": [models.Index(fields=["finished_at"], name="gath_task_finished_idx")],
            },
        ),
        migrations.CreateModel(
            name="DeviceGatheringResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("SKIPPED", "Skipped"),
                            ("FAILURE", "Failure"),
                        ],
                        db_index=True,
                        default="RUNNING",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("error_type", models.CharField(blank=True, max_length=128, verbose_name="Тип ошибки")),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата начала"),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gathering_results",
                        to="check.devices",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_results",
                        to="gathering.gatheringtask",
                    ),
                ),
            ],
            options={
                "db_table": "device_gathering_results",
                "ordering": ("-started_at",),
                "constraints": [
                    models.UniqueConstraint(fields=("task", "device"), name="uniq_gath_task_device")
                ],
            },
        ),
    ]
