# Generated by Django 6.0.8 on 2026-08-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gathering", "0005_gatheringtask_devicegatheringresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macaddress",
            name="desc",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="desc",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
