# Generated by Django 4.1.7 on 2023-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberconnection",
            name="description",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
