# Generated by Django 4.1.7 on 2023-05-12 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("check", "0024_interfacescomments_datetime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RingDev",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ring_name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Названия кольца, где будет данное устройство",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Выберите устройство, которое находится в кольце",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check.devices",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "next_dev",
                    models.ForeignKey(
                        blank=True,
                        help_text="Начиная от головного устройства укажите следующее за данным",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_node",
                        to="ring_manager.ringdev",
                        verbose_name="Следующее устройство",
                    ),
                ),
                (
                    "prev_dev",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prev_node",
                        to="ring_manager.ringdev",
                        verbose_name="Предыдущее устройство",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportRing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Это название будет отображаться в меню колец",
                        max_length=100,
                        unique=True,
                        verbose_name="Название кольца",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "vlans",
                    models.TextField(
                        help_text="Укажите через запятую, какие VLAN необходимо добавить для оконечного оборудования в кольце в случае разворота",
                        verbose_name="VLAN'S",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Штатное состояние"),
                            ("DEACTIVATED", "Деактивировано"),
                            ("IN_PROCESS", "Занято в данный момент"),
                        ],
                        default="NORMAL",
                        help_text="Какое в данный момент состояние имеет кольцо",
                        max_length=20,
                        verbose_name="Состояние кольца",
                    ),
                ),
                ("solution_time", models.DateTimeField(blank=True, null=True)),
                ("solutions", models.JSONField(blank=True, default=list, null=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        help_text="Необходимо для начала создать головную точку, а затем выбрать её. Данная точка будет ведущей в кольце.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="head_node",
                        to="ring_manager.ringdev",
                        verbose_name="Головное устройство",
                    ),
                ),
                (
                    "tail",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для данного оборудования будут добавляться VLAN в случае разворота кольца",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tail_node",
                        to="ring_manager.ringdev",
                        verbose_name="Оконечная точка в кольце.",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="Выберите, кто будет иметь доступ к кольцу",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи",
                    ),
                ),
            ],
        ),
    ]
