# Generated by Django 4.0.6 on 2022-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="vendor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
