# Generated by Django 4.0.6 on 2022-07-27 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0002_devices_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("login", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=64)),
                ("secret", models.CharField(default="sevaccess", max_length=64)),
            ],
        ),
        migrations.AlterModelTable(
            name="devicegroup",
            table="device_groups",
        ),
        migrations.AlterModelTable(
            name="devices",
            table="devices",
        ),
        migrations.AddField(
            model_name="devices",
            name="auth_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="check.authgroup",
            ),
        ),
    ]
