# Generated by Django 4.0.6 on 2022-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0004_alter_authgroup_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("ip", models.CharField(max_length=15, unique=True)),
                ("login", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=64)),
                ("secret", models.CharField(default="sevaccess", max_length=64)),
            ],
            options={
                "db_table": "bras",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="authgroup",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="devicegroup",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="devices",
            options={"ordering": ("ip",)},
        ),
    ]
