# Generated by Django 4.0.7 on 2022-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0007_remove_profile_id_alter_profile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devices",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="devices",
            name="snmp_community",
            field=models.CharField(default="inline2014", max_length=64),
        ),
    ]
