# Generated by Django 4.0.7 on 2022-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0008_alter_devices_options_devices_snmp_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="protocol",
            field=models.CharField(default="telnet", max_length=6),
        ),
    ]
