# Generated by Django 4.0.7 on 2022-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0009_devices_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="devices",
            name="protocol",
            field=models.CharField(
                choices=[("snmp", "snmp"), ("telnet", "telnet"), ("ssh", "ssh")],
                default="telnet",
                max_length=6,
            ),
        ),
    ]
