# Generated by Django 4.0.7 on 2022-08-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0010_alter_devices_name_alter_devices_protocol"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authgroup",
            options={
                "ordering": ("name",),
                "verbose_name": "Auth group",
                "verbose_name_plural": "Auth groups",
            },
        ),
        migrations.AlterModelOptions(
            name="bras",
            options={
                "ordering": ("name",),
                "verbose_name": "BRAS",
                "verbose_name_plural": "BRASes",
            },
        ),
        migrations.AlterModelOptions(
            name="devicegroup",
            options={
                "ordering": ("name",),
                "verbose_name": "Device group",
                "verbose_name_plural": "Device groups",
            },
        ),
        migrations.AlterModelOptions(
            name="devices",
            options={
                "ordering": ("name",),
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("user",),
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterModelTable(
            name="bras",
            table="brases",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="user_profiles",
        ),
    ]
