# Generated by Django 4.0.7 on 2022-08-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0011_alter_authgroup_options_alter_bras_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicegroup",
            name="user",
        ),
        migrations.AddField(
            model_name="profile",
            name="devices_groups",
            field=models.ManyToManyField(to="check.devicegroup"),
        ),
    ]
