# Generated by Django 4.0.7 on 2022-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0013_authgroup_description_devicegroup_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="model",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Модель (Обновляется автоматически)",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="vendor",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Производитель (Обновляется автоматически)",
            ),
        ),
    ]
