# Generated by Django 4.0.7 on 2022-09-08 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("check", "0018_usersactions_usersactions_logs_time_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersactions",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="check.devices",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="usersactions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
