# Generated by Django 4.0.7 on 2022-09-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0020_alter_usersactions_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogsElasticStackSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kibana_url",
                    models.CharField(
                        blank=True,
                        help_text="Например: http://kibana:5601/app/discover#/",
                        max_length=100,
                        null=True,
                        verbose_name="Kibana discover URL",
                    ),
                ),
                (
                    "time_range",
                    models.CharField(
                        blank=True,
                        help_text="Например: 1d, 24h или 30m",
                        max_length=4,
                        null=True,
                        verbose_name="Глубина временного диапазона",
                    ),
                ),
                (
                    "output_columns",
                    models.CharField(
                        blank=True,
                        help_text="Поля через запятую, которые должны отображаться как колонки. Например: message, host.ip",
                        max_length=255,
                        null=True,
                        verbose_name="Колонки",
                    ),
                ),
                (
                    "query_lang",
                    models.CharField(
                        blank=True,
                        choices=[("KQL", "KQL"), ("Lucene", "Lucene")],
                        default="KQL",
                        help_text='<a href="https://www.elastic.co/guide/en/kibana/8.4/kuery-query.html">Documentation</a>',
                        max_length=10,
                        null=True,
                        verbose_name="Язык запросов",
                    ),
                ),
                (
                    "query_str",
                    models.CharField(
                        blank=True,
                        help_text='Необходимо указать, как будет произведен поиск логов для отдельного устройства.<br>Например: "host.ip : {device.ip}"',
                        max_length=255,
                        null=True,
                        verbose_name="Строка для поиска",
                    ),
                ),
                (
                    "time_field",
                    models.CharField(
                        blank=True,
                        help_text="Сортировка будет происходить по нему. Например: @timestamp",
                        max_length=100,
                        null=True,
                        verbose_name="timestamp поле",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="usersactions",
            options={
                "ordering": ("-time",),
                "verbose_name": "User Action",
                "verbose_name_plural": "Users Actions",
            },
        ),
    ]
