# Generated by Django 4.1.4 on 2023-01-13 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("check", "0022_delete_logselasticstacksettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterfacesComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interface", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="check.devices"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к интерфейсу",
                "verbose_name_plural": "Комментарии к интерфейсам",
                "db_table": "interfaces_comments",
            },
        ),
    ]
