# Generated by Django 4.1.7 on 2023-07-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0025_devicemedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemedia",
            name="description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
