# Generated by Django 4.1.7 on 2023-11-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0026_alter_devicemedia_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="port_guard_pattern",
            field=models.CharField(
                blank=True,
                help_text="Регулярное выражение, совпадение которого с описанием порта будет запрещать определенные действия с ним",
                max_length=500,
                null=True,
                verbose_name="Защитный RegExp для описания порта",
            ),
        ),
    ]
