# Generated by Django 5.1.5 on 2025-02-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0030_bras_connection_pool_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="collect_vlan_info",
            field=models.BooleanField(
                default=True,
                help_text='Если включено, то будет собрана VLAN информация во время периодической задачи "vlan_table_gather_task"',
                verbose_name="Сбор VLAN информации",
            ),
        ),
    ]
