# Generated by Django 5.1.5 on 2025-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("check", "0030_bras_connection_pool_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("read", "Чтение"),
                    ("reboot", "Перезагрузка порта"),
                    ("up_down", "Изменение состояния порта"),
                    ("bras", "Сброс сессий клиента"),
                    ("cmd_run", "Выполнение команд"),
                ],
                default="read",
                max_length=15,
                verbose_name="Уровень доступа",
            ),
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Кратко, что она делает",
                        max_length=100,
                        verbose_name="Название команды",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание команды"
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text="Вы можете использовать макросы - {port}, чтобы подставить название интерфейса, а также {ip}, {mac}",
                        max_length=512,
                        verbose_name="Команда",
                    ),
                ),
                (
                    "device_vendor",
                    models.CharField(
                        help_text="Команда будет доступна только оборудованию с тем же вендором",
                        max_length=100,
                        verbose_name="Вендор",
                    ),
                ),
                (
                    "perm_groups",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="Права доступа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда для оборудования",
                "verbose_name_plural": "Команды для оборудования",
                "db_table": "device_commands",
            },
        ),
    ]
