# Generated by Django 5.1.5 on 2025-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0032_merge_20250223_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicecommand",
            name="model_regexp",
            field=models.CharField(
                blank=True,
                help_text="Команда будет доступна только оборудованию с той же моделью",
                max_length=512,
                null=True,
                verbose_name="Регулярное выражение для модели",
            ),
        ),
        migrations.AlterField(
            model_name="devicecommand",
            name="command",
            field=models.TextField(
                help_text="Вы можете использовать макросы - {port}, чтобы подставить название интерфейса, а также {ip}, {mac}",
                verbose_name="Команды",
            ),
        ),
    ]
