# Generated by Django 5.1.5 on 2025-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0033_devicecommand_model_regexp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="os_version",
            field=models.CharField(
                blank=True,
                help_text="Если не указано, то обновится автоматически при подключении к устройству",
                max_length=512,
                null=True,
                verbose_name="Версия ПО",
            ),
        ),
    ]
