# Generated by Django 5.2 on 2025-04-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0034_devices_os_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="auth_group",
            field=models.ForeignKey(
                help_text="Указываем группу, для удаленного подключения к оборудованию. Используется для протоколов telnet и ssh. Если на оборудовании логин/пароль из указанной группы не подошли, то будут автоматически подбираться пары логин/пароль по очереди, указанной в этом списке (кроме неверного)",
                on_delete=django.db.models.deletion.PROTECT,
                to="check.authgroup",
                verbose_name="Группа авторизации",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="check.devicegroup",
                verbose_name="Группа",
            ),
        ),
    ]
