# Generated by Django 4.1.2 on 2022-12-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logselasticstacksettings",
            name="query_lang",
            field=models.CharField(
                blank=True,
                choices=[("kuery", "KQL"), ("lucene", "Lucene")],
                default="KQL",
                help_text='<a target="_blank" href="https://www.elastic.co/guide/en/kibana/8.4/kuery-query.html">Documentation</a>',
                max_length=10,
                null=True,
                verbose_name="Язык запросов",
            ),
        ),
    ]
