# Generated by Django 5.1.1 on 2024-10-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0002_alter_logselasticstacksettings_query_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="vlantracerouteconfig",
            name="cache_timeout",
            field=models.IntegerField(
                default=300, verbose_name="Время в секундах для кеширования"
            ),
        ),
        migrations.AddField(
            model_name="vlantracerouteconfig",
            name="ip_pattern",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Используется для того, чтобы найти оборудования, с которых начинается трассировка",
                null=True,
                verbose_name="Регулярное выражение для указания IP",
            ),
        ),
        migrations.AddField(
            model_name="vlantracerouteconfig",
            name="vlan_start_regex",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Используется для того, чтобы найти оборудования, с которых начинается трассировка",
                null=True,
                verbose_name="Регулярное выражение",
            ),
        ),
        migrations.AlterField(
            model_name="vlantracerouteconfig",
            name="vlan_start",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Разделять необходимо переносом строки, если требуется указать несколько",
                null=True,
                verbose_name="Имя оборудования для начала трассировки",
            ),
        ),
    ]
