# Generated by Django 4.0.7 on 2022-09-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0016_alter_authgroup_options_remove_devices_protocol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bras",
            name="ip",
            field=models.GenericIPAddressField(protocol="ipv4", unique=True, verbose_name="IP адрес"),
        ),
    ]
