# Generated by Django 4.0.7 on 2022-09-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0019_alter_usersactions_device_alter_usersactions_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersactions",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="check.devices",
                verbose_name="Оборудование",
            ),
        ),
    ]
