# Generated by Django 5.0.3 on 2024-03-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0027_profile_port_guard_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="console_access",
            field=models.BooleanField(
                default=False,
                help_text="Доступ к консоли сервера удаленных подключений",
                verbose_name="Доступ к консоли",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="console_url",
            field=models.CharField(default="", max_length=500, blank=True, verbose_name="URL консоли"),
        ),
    ]
