# Generated by Django 5.1.1 on 2024-12-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0028_profile_console_access_profile_console_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AddField(
            model_name="devices",
            name="collect_configurations",
            field=models.BooleanField(
                default=True,
                help_text='Если включено, то будут собраны конфигурации во время периодической задачи "configuration_gather_task"',
                verbose_name="Сбор конфигураций",
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="collect_interfaces",
            field=models.BooleanField(
                default=True,
                help_text='Если включено, то будут собраны интерфейсы во время периодической задачи "interfaces_scan"',
                verbose_name="Сбор интерфейсов",
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="collect_mac_addresses",
            field=models.BooleanField(
                default=True,
                help_text='Если включено, то будут собраны MAC адреса во время периодической задачи "mac_table_gather_task"',
                verbose_name="Сбор MAC адресов",
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="interface_pattern",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Паттерн, по которому отфильтрованы интерфейсы. Например `^gi\\S+|^eth\\S+`. По умолчанию все интерфейсы.",
                max_length=255,
                verbose_name="Паттерн имени интерфейса",
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Если не указано, то обновится автоматически при подключении к устройству",
                max_length=255,
                null=True,
                verbose_name="Серийный номер",
            ),
        ),
    ]
