# Generated by Django 5.1.5 on 2025-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0029_devices_active_devices_collect_configurations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bras",
            name="connection_pool_size",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Количество подключений к оборудованию, которые могут быть одновременно открыты",
                verbose_name="Размер пула подключений",
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="connection_pool_size",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Количество подключений к оборудованию, которые могут быть одновременно открыты",
                verbose_name="Размер пула подключений",
            ),
        ),
    ]
