# Generated by Django 5.1.5 on 2025-02-23 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0031_alter_profile_permissions_devicecommand"),
        ("check", "0031_devices_collect_vlan_info"),
    ]

    operations = []
