# Generated by Django 5.2 on 2025-08-07 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("check", "0035_alter_devices_auth_group_alter_devices_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="access_groups",
                        to="check.devices",
                        verbose_name="Разрешенное оборудование",
                    ),
                ),
                (
                    "forbidden_devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="forbidden_access_groups",
                        to="check.devices",
                        verbose_name="Запрещенное оборудование",
                    ),
                ),
                (
                    "user_groups",
                    models.ManyToManyField(blank=True, to="auth.group", verbose_name="Группы пользователей"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи",
                    ),
                ),
            ],
            options={
                "db_table": "access_groups",
            },
        ),
    ]
