# Generated by Django 6.0.3 on 2026-04-06 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0036_accessgroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkDeviceCommandExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Celery task ID"
                    ),
                ),
                (
                    "command_name",
                    models.CharField(max_length=100, verbose_name="Command name"),
                ),
                ("command_body", models.TextField(verbose_name="Command body")),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Command context"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROGRESS", "PROGRESS"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("REVOKED", "REVOKED"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Progress"
                    ),
                ),
                (
                    "processed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Processed devices"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total devices"
                    ),
                ),
                (
                    "launched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Launched at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_executions",
                        to="check.devicecommand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_device_command_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk device command execution",
                "verbose_name_plural": "Bulk device command executions",
                "db_table": "bulk_device_command_executions",
                "ordering": ("-launched_at",),
            },
        ),
        migrations.CreateModel(
            name="BulkDeviceCommandExecutionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="Device name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCESS", "SUCCESS"),
                            ("ERROR", "ERROR"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "command_text",
                    models.TextField(blank=True, verbose_name="Rendered command text"),
                ),
                ("output", models.TextField(blank=True, verbose_name="Output")),
                ("detail", models.TextField(blank=True, verbose_name="Detail")),
                ("error", models.TextField(blank=True, verbose_name="Error")),
                ("duration", models.FloatField(default=0, verbose_name="Duration")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_command_results",
                        to="check.devices",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="check.bulkdevicecommandexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk command execution result",
                "verbose_name_plural": "Bulk command execution results",
                "db_table": "bulk_device_command_execution_results",
                "ordering": ("device_name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("execution", "device"),
                        name="bulk_device_command_execution_device_unique",
                    )
                ],
            },
        ),
    ]
