# Generated by Django 6.0.3 on 2026-04-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0037_bulkdevicecommandexecution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicecommand",
            name="valid_regexp",
            field=models.CharField(
                blank=True,
                help_text="Проверяет, что команда верно выполнилась",
                max_length=512,
                null=True,
                verbose_name="Регулярное выражение проверки",
            ),
        ),
    ]
