# Generated by Django 6.0.5 on 2026-05-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0038_devicecommand_valid_regexp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkdevicecommandexecutionresult",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Bulk command execution result",
                "verbose_name_plural": "Bulk command execution results",
            },
        ),
    ]
