# Generated by Django 6.0.5 on 2026-05-22 19:08

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0039_alter_bulkdevicecommandexecutionresult_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90")),
                    django.core.validators.MaxValueValidator(Decimal("90")),
                ],
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180")),
                    django.core.validators.MaxValueValidator(Decimal("180")),
                ],
                verbose_name="Долгота",
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="snmp_port",
            field=models.PositiveSmallIntegerField(
                default=161,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="ssh_port",
            field=models.PositiveSmallIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name="devices",
            name="telnet_port",
            field=models.PositiveSmallIntegerField(
                default=23,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="device_console_url",
            field=models.CharField(
                blank=True,
                default="{protocol}://{ip}",
                help_text="Вы можете использовать макросы, чтобы подставить значения. Доступны: {ip}, {name}, {username} и {protocol}",
                max_length=500,
                verbose_name="URL консоли оборудования",
            ),
        ),
    ]
