# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0040_devices_latitude_devices_longitude_devices_snmp_port_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceInterfacePatternRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("enabled", models.BooleanField(default=True, verbose_name="Включено")),
                (
                    "vendor",
                    models.CharField(
                        help_text="Правило применяется только к оборудованию этого вендора.",
                        max_length=100,
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "model_pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Пустое значение означает все модели указанного производителя.",
                        max_length=255,
                        verbose_name="Шаблон модели",
                    ),
                ),
                (
                    "model_match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Точное совпадение"),
                            ("contains", "Содержит"),
                            ("regexp", "RegExp"),
                        ],
                        default="exact",
                        max_length=8,
                        verbose_name="Тип совпадения модели",
                    ),
                ),
                (
                    "interface_pattern",
                    models.CharField(
                        help_text="RegExp, по которому будут оставлены интерфейсы. Например: `^Gi|^Fa`.",
                        max_length=255,
                        verbose_name="Паттерн имени интерфейса",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="При равной специфичности выбирается правило с большим приоритетом.",
                        verbose_name="Приоритет",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Правило паттерна интерфейсов",
                "verbose_name_plural": "Правила паттернов интерфейсов",
                "db_table": "device_interface_pattern_rules",
                "ordering": ("vendor", "model_pattern", "-priority", "id"),
                "indexes": [
                    models.Index(fields=["enabled"], name="dev_int_pat_enabled_idx"),
                    models.Index(fields=["vendor"], name="dev_int_pat_vendor_idx"),
                    models.Index(fields=["vendor", "enabled"], name="dev_int_pat_vendor_enabled_idx"),
                    models.Index(
                        fields=["vendor", "model_match_type", "model_pattern"],
                        name="dev_int_pat_model_idx",
                    ),
                ],
            },
        ),
    ]
