# Generated by Django 4.0.7 on 2022-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesInfo',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('interfaces', models.TextField(null=True)),
                ('interfaces_date', models.DateTimeField(null=True)),
                ('sys_info', models.TextField(null=True)),
                ('sys_info_date', models.DateTimeField(null=True)),
                ('vlans', models.TextField(null=True)),
                ('vlans_date', models.DateTimeField(null=True)),
                ('device_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'device_info',
                'ordering': ('ip',),
            },
        ),
    ]
