# Generated by Django 4.1.4 on 2023-01-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0023_interfacescomments"),
        ("net_tools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicesinfo",
            name="sys_info",
        ),
        migrations.RemoveField(
            model_name="devicesinfo",
            name="sys_info_date",
        ),
        migrations.AddField(
            model_name="devicesinfo",
            name="dev",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="check.devices",
            ),
        ),
    ]
