# Generated by Django 4.0.7 on 2022-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesinfo',
            name='device_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
