# Generated by Django 4.0.7 on 2022-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_tools', '0002_alter_devicesinfo_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescNameFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=255, unique=True, verbose_name='Необходимое имя оборудования')),
                ('replacement', models.TextField(verbose_name='Возможные варианты (через запятую)')),
            ],
            options={
                'verbose_name': 'VLAN traceroute desc name format',
                'db_table': 'vlan_traceroute_desc_name_format',
            },
        ),
    ]
