# Generated by Django 4.0.7 on 2022-10-04 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_tools', '0003_descnameformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlanName',
            fields=[
                ('vid', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4096)], verbose_name='VLAN id')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'db_table': 'vlan_name',
            },
        ),
    ]
