# Generated by Django 4.0.7 on 2022-10-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0022_delete_logselasticstacksettings'),
        ('net_tools', '0004_vlanname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesForMacSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('device', models.ForeignKey(help_text='Будет искать MAC в таблице arp оборудования', on_delete=django.db.models.deletion.CASCADE, to='check.devices', verbose_name='Оборудование для поиска MAC')),
            ],
        ),
    ]
