# Generated by Django 4.0.7 on 2022-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_tools', '0005_devicesformacsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesformacsearch',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
