# Generated by Django 5.2 on 2025-06-12 15:52

from django.db import migrations, models

import accounting.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_userapitoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapitoken",
            name="allowed_ips",
            field=models.TextField(
                blank=True,
                help_text="Укажите IP адреса через запятую. Можно указывать подсети в формате 192.168.0.0/24",
                validators=[accounting.models.validate_ip_addresses],
                verbose_name="Allowed IPs",
            ),
        ),
    ]
