# Generated by Django 5.2.12 on 2026-03-15 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("check", "0036_accessgroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTrigger",
            fields=[
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "notification_triggers",
            },
        ),
        migrations.CreateModel(
            name="NotificationCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Смотрите <a href="https://github.com/ig-rudenko/ecstasy/wiki" target="_blank">wiki</a>',
                        max_length=512,
                        verbose_name="Название условия",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Включает проверку данного условия."
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Перечень конкретного оборудования, если не указано, то все.",
                        related_name="notification_conditions",
                        to="check.devices",
                        verbose_name="Перечень оборудования",
                    ),
                ),
                (
                    "devices_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Перечень групп оборудования, если не указано, то все.",
                        related_name="notification_conditions",
                        to="check.devicegroup",
                        verbose_name="Группы оборудования",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notification_conditions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи",
                    ),
                ),
                (
                    "users_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Перечень групп пользователей, если не указано, то все.",
                        related_name="notification_conditions",
                        to="auth.group",
                        verbose_name="Группы пользователей",
                    ),
                ),
                (
                    "triggers",
                    models.ManyToManyField(
                        help_text="Какие действия будут провоцировать оповещение.",
                        related_name="notification_conditions",
                        to="notifications.notificationtrigger",
                        verbose_name="Триггеры",
                    ),
                ),
            ],
            options={
                "db_table": "notification_conditions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=512, verbose_name="Название оповещения"
                    ),
                ),
                (
                    "telegram_api_url",
                    models.CharField(
                        default="https://api.telegram.org/",
                        max_length=2048,
                        verbose_name="Telegram API URL",
                    ),
                ),
                ("bot_token", models.CharField(max_length=256)),
                (
                    "chat_id",
                    models.CharField(
                        help_text="Уникальный идентификатор целевого чата или имя пользователя целевого канала.",
                        max_length=256,
                    ),
                ),
                (
                    "message_thread_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Уникальный идентификатор целевой ветки сообщений (темы) форума; только для супергрупп-форумов.",
                        null=True,
                    ),
                ),
                (
                    "business_connection_id",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный идентификатор бизнес-аккаунта, от которого было получено сообщение. Если значение не пустое, сообщение относится к чату соответствующего бизнес-аккаунта, который не связан с потенциальным ботом, который может иметь тот же идентификатор.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "parse_mode",
                    models.CharField(
                        choices=[
                            ("HTML", "Html"),
                            ("Markdown", "Markdown"),
                            ("MarkdownV2", "Markdownv2"),
                        ],
                        default="HTML",
                        max_length=16,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Активно ли оповещение."
                    ),
                ),
                (
                    "disable_notification",
                    models.BooleanField(
                        default=False,
                        help_text="Отправляет сообщение беззвучно. Пользователи получат уведомление без звука.",
                    ),
                ),
                (
                    "protect_content",
                    models.BooleanField(
                        default=False,
                        help_text="Защищает содержимое отправленного сообщения от пересылки и сохранения.",
                    ),
                ),
                (
                    "message_effect_id",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный идентификатор эффекта сообщения, который будет добавлен к сообщению; только для личных чатов",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст отправляемого сообщения. 1-4096 символов после обработки сущностей!\nПоддерживается шаблонизатор Django, передаваемые объекты: device, result, request, user",
                        max_length=4096,
                    ),
                ),
                (
                    "reply_markup",
                    models.JSONField(
                        blank=True,
                        help_text="Дополнительные параметры интерфейса. Объект в формате JSON для встроенной клавиатуры, пользовательской клавиатуры ответа, инструкций по удалению клавиатуры ответа или принудительному ответу от пользователя",
                        null=True,
                    ),
                ),
                (
                    "notification_conditions",
                    models.ManyToManyField(
                        help_text="Если условий несколько, то будет выбрано хотя бы одно сработанное.\nРеализуется логическое ИЛИ.",
                        related_name="telegram_notifications",
                        to="notifications.notificationcondition",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_by_telegram",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationcondition",
            index=models.Index(fields=["active"], name="notif_cond_active_index"),
        ),
        migrations.AddIndex(
            model_name="telegramnotification",
            index=models.Index(fields=["active"], name="notif_telegram_active_index"),
        ),
    ]
