# Generated by Django 6.0.5 on 2026-05-21 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("check", "0039_alter_bulkdevicecommandexecutionresult_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(protocol="ipv4", unique=True, verbose_name="IP адрес"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Предложенное имя"),
                ),
                (
                    "vendor",
                    models.CharField(blank=True, max_length=100, verbose_name="Производитель"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Модель"),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, verbose_name="Серийный номер"),
                ),
                (
                    "os_version",
                    models.CharField(blank=True, max_length=512, verbose_name="Версия ПО"),
                ),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=64, verbose_name="MAC адрес"),
                ),
                (
                    "sys_name",
                    models.CharField(blank=True, max_length=255, verbose_name="SNMP sysName"),
                ),
                (
                    "sys_descr",
                    models.TextField(blank=True, verbose_name="SNMP sysDescr"),
                ),
                (
                    "sys_object_id",
                    models.CharField(blank=True, max_length=255, verbose_name="SNMP sysObjectID"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PING", "Ping"),
                            ("TCP", "TCP"),
                            ("SNMP", "SNMP"),
                            ("CLI", "CLI"),
                            ("ZABBIX_IMPORT", "Zabbix import"),
                        ],
                        default="PING",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("READY", "Ready"),
                            ("DUPLICATE", "Duplicate"),
                            ("CREATED", "Created"),
                            ("IGNORED", "Ignored"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Confidence"),
                ),
                (
                    "detected_protocols",
                    models.JSONField(blank=True, default=dict, verbose_name="Найденные протоколы"),
                ),
                (
                    "selected_snmp_community",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Выбранный SNMP community",
                    ),
                ),
                (
                    "raw_fingerprint",
                    models.JSONField(blank=True, default=dict, verbose_name="Сырой fingerprint"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Первое обнаружение"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Последнее обнаружение",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_candidate",
                        to="check.devices",
                        verbose_name="Созданное оборудование",
                    ),
                ),
                (
                    "selected_auth_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_candidates",
                        to="check.authgroup",
                        verbose_name="Выбранная группа авторизации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery candidate",
                "verbose_name_plural": "Discovery candidates",
                "db_table": "discovery_candidates",
                "ordering": ("-last_seen_at", "ip"),
            },
        ),
        migrations.CreateModel(
            name="DiscoveryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Название"),
                ),
                (
                    "networks",
                    models.JSONField(default=list, verbose_name="IPv4 подсети"),
                ),
                (
                    "exclude_ips",
                    models.JSONField(blank=True, default=list, verbose_name="Исключенные IP/CIDR"),
                ),
                (
                    "snmp_communities",
                    models.JSONField(blank=True, default=list, verbose_name="SNMP communities"),
                ),
                (
                    "try_protocols",
                    models.JSONField(blank=True, default=list, verbose_name="CLI протоколы"),
                ),
                (
                    "port_scan_protocol",
                    models.CharField(
                        choices=[
                            ("snmp", "snmp"),
                            ("telnet", "telnet"),
                            ("ssh", "ssh"),
                        ],
                        default="snmp",
                        max_length=6,
                        verbose_name="Протокол сбора интерфейсов",
                    ),
                ),
                (
                    "cmd_protocol",
                    models.CharField(
                        choices=[("telnet", "telnet"), ("ssh", "ssh")],
                        default="ssh",
                        max_length=6,
                        verbose_name="Протокол выполнения команд",
                    ),
                ),
                (
                    "max_workers",
                    models.PositiveSmallIntegerField(default=32, verbose_name="Параллельность"),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(default=2, verbose_name="Таймаут"),
                ),
                (
                    "auto_create",
                    models.BooleanField(default=False, verbose_name="Автосоздание"),
                ),
                (
                    "auto_create_min_confidence",
                    models.PositiveSmallIntegerField(
                        default=70,
                        verbose_name="Минимальный confidence для автосоздания",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "auth_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discovery_profiles",
                        to="check.authgroup",
                        verbose_name="Группы авторизации",
                    ),
                ),
                (
                    "device_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_profiles",
                        to="check.devicegroup",
                        verbose_name="Группа оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery profile",
                "verbose_name_plural": "Discovery profiles",
                "db_table": "discovery_profiles",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DiscoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Celery task ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROGRESS", "Progress"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(default=0, verbose_name="Всего адресов"),
                ),
                (
                    "processed",
                    models.PositiveIntegerField(default=0, verbose_name="Обработано"),
                ),
                (
                    "found",
                    models.PositiveIntegerField(default=0, verbose_name="Найдено"),
                ),
                (
                    "created",
                    models.PositiveIntegerField(default=0, verbose_name="Создано устройств"),
                ),
                (
                    "skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено"),
                ),
                (
                    "errors",
                    models.PositiveIntegerField(default=0, verbose_name="Ошибок"),
                ),
                (
                    "dry_run",
                    models.BooleanField(default=False, verbose_name="Пробный запуск"),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Сводка"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Запустил",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="discovery.discoveryprofile",
                        verbose_name="Профиль discovery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery run",
                "verbose_name_plural": "Discovery runs",
                "db_table": "discovery_runs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DiscoveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(protocol="ipv4", verbose_name="IP адрес"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PING", "Ping"),
                            ("TCP_22", "TCP 22"),
                            ("TCP_23", "TCP 23"),
                            ("TCP_161", "TCP 161"),
                            ("SNMP", "SNMP"),
                            ("SSH", "SSH"),
                            ("TELNET", "Telnet"),
                        ],
                        max_length=20,
                        verbose_name="Метод",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                            ("AUTH_FAILED", "Auth failed"),
                            ("UNSUPPORTED", "Unsupported"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="Длительность, мс"),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="discovery.discoverycandidate",
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="discovery.discoveryrun",
                        verbose_name="Запуск discovery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery attempt",
                "verbose_name_plural": "Discovery attempts",
                "db_table": "discovery_attempts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="discoverycandidate",
            index=models.Index(
                fields=["status", "last_seen_at"],
                name="disc_cand_status_seen",
            ),
        ),
        migrations.AddIndex(
            model_name="discoverycandidate",
            index=models.Index(fields=["serial_number"], name="disc_cand_serial"),
        ),
        migrations.AddIndex(
            model_name="discoveryattempt",
            index=models.Index(fields=["run", "ip"], name="disc_attempt_run_ip"),
        ),
        migrations.AddIndex(
            model_name="discoveryattempt",
            index=models.Index(fields=["method", "status"], name="disc_attempt_method_status"),
        ),
    ]
