# Generated by Django 6.0.6 on 2026-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveryprofile",
            name="activate_created_devices",
            field=models.BooleanField(default=False, verbose_name="Активировать созданное оборудование"),
        ),
    ]
