name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DJANGO_SECRET_KEY: qwerty*!(#*JJSAJ_!@+uiop1234567890
  DATABASES: |
      {
          "default": {
              "ENGINE": "django.db.backends.mysql",
              "NAME": "ecstasy",
              "USER": "root",
              "PASSWORD": "root_password",
              "HOST": "127.0.0.1",
              "PORT": "3306"
          }
      }

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      database:
        image: mysql
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          MYSQL_ROOT_PASSWORD: "root_password"
          MYSQL_USER: "user"
          MYSQL_PASSWORD: "password"
          MYSQL_DATABASE: "ecstasy"

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Run Tests
      run: |
        coverage run manage.py test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
